### PR TITLE
V6

### PR DESCRIPTION
**Pull request by jamesfer**
- Adds support for Neo4j v4 🎉
- Removes any-promise and any-observable

### CODE REVIEW

**Comment by bboure** [comment]
@jamesfer What's the status on this?
Would be great to have neo4j v4 support.
Let me know if you need help

**Comment by jamesfer** [comment]
Hey @bboure, thanks for the comment. 

Sorry I've left this project for a while, but I managed to get this branch merged so V6 should deploy in a few minutes. Please let me know if you run into more issues 😁

**Comment by bboure** [comment]
@jamesfer awesome thanks. I'll give it a shot.

**Pull request merged**
